# Generated by Django 4.1.7 on 2023-04-07 10:32

import Accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_customuser_is_superuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', Accounts.models.CustomUserManager()),
            ],
        ),
    ]
