"""
Django settings for Notes project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key.txt used in production secret!
with open(BASE_DIR / 'Server/key.txt', 'r') as file:
    SECRET_KEY = file.read()


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sslserver',
    'Planner',
    'Accounts',
    'django_celery_beat',
    'Djangoserver_plus',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'Server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'Planner/templates',
                 BASE_DIR / 'Accounts/templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Server.wsgi.application'

CSRF_TRUSTED_ORIGINS = ['https://adapt-notes.up.railway.app']

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'Notes',
        'USER': 'root',
        'PASSWORD': '0mn1v35s4',
        #'PASSWORD': 'Hs66pMMH3E9vuFkfFm04',
        #'HOST': 'localhost',#'containers-us-west-10.railway.app',
        #'PORT': '6123'
        },
    }


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = "Asia/Kolkata"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'Server/staticfiles'
STATICFILES_DIRS = (
    (BASE_DIR / 'Planner' / STATIC_URL),
    (BASE_DIR / 'Accounts' / STATIC_URL),
)

# Default primary key.txt field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# to make sure django uses my custom defined authentication model to handle all
# login and sign in tasks.
AUTH_USER_MODEL = "Accounts.CustomUser"

# CELERY settings.

# broker url?
# PORT : 6379 and DATABASE IN USE: 0
#CELERY_BROKER_URL = "redis://localhost:6379/0"
# Deprecated feature, as development has been moved to
# windows.

CELERY_POOL = 'gevent'
CELERY_CONCURRENCY = 1000

CELERY_BEAT_POOL = 'gevent'
CELERY_BEAT_CONCURRENCY = 1

CELERY_BEAT_SCHEDULE = {
    'scheduled_task': {
        'task': 'Planner.tasks.run_whats_interface',
        'schedule': 30,
    },
}
