# Generated by Django 4.1.7 on 2023-04-14 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Interaction_Details',
            fields=[
                ('Username', models.CharField(default='AddedBefore', max_length=30, primary_key=True, serialize=False)),
                ('LLogin', models.DateTimeField()),
                ('LInteract', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('Priority', models.AutoField(primary_key=True, serialize=False)),
                ('Task', models.CharField(max_length=300)),
                ('Add_On', models.DateTimeField(auto_now_add=True)),
                ('DeadLine', models.DateTimeField(default='1900-12-12 12:12:12')),
                ('NextUpdate', models.DateTimeField(default='1900-12-12 12:12:12')),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Planner.user_interaction_details')),
            ],
        ),
    ]
