# Generated by Django 4.1.7 on 2023-03-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planner',
            old_name='DeadLine',
            new_name='Deadline',
        ),
        migrations.AlterField(
            model_name='planner',
            name='Priority',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
